// <auto-generated />
using BattleGameWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BattleGameWebAPI.Migrations
{
    [DbContext(typeof(BattleGameDatabase))]
    [Migration("20250903181251_PlayerProfile_AccountData_OneToOne_WithBaseData")]
    partial class PlayerProfile_AccountData_OneToOne_WithBaseData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BattleGameWebAPI.Models.AccountData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseDataId")
                        .HasColumnType("int");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<int>("PlayerProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaseDataId");

                    b.HasIndex("PlayerProfileId")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("BattleGameWebAPI.Models.BaseData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("BaseData");
                });

            modelBuilder.Entity("BattleGameWebAPI.Models.PlayerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountDataId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("BattleGameWebAPI.Models.SquadData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseDataId")
                        .HasColumnType("int");

                    b.Property<int>("UnitCount")
                        .HasColumnType("int");

                    b.Property<int>("UnitTemplateDataId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaseDataId");

                    b.HasIndex("UnitTemplateDataId");

                    b.ToTable("SquadData");
                });

            modelBuilder.Entity("BattleGameWebAPI.Models.UnitTemplateData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UnitTemplateData");
                });

            modelBuilder.Entity("BattleGameWebAPI.Models.AccountData", b =>
                {
                    b.HasOne("BattleGameWebAPI.Models.BaseData", "Base")
                        .WithMany()
                        .HasForeignKey("BaseDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BattleGameWebAPI.Models.PlayerProfile", "PlayerProfile")
                        .WithOne("AccountData")
                        .HasForeignKey("BattleGameWebAPI.Models.AccountData", "PlayerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Base");

                    b.Navigation("PlayerProfile");
                });

            modelBuilder.Entity("BattleGameWebAPI.Models.SquadData", b =>
                {
                    b.HasOne("BattleGameWebAPI.Models.BaseData", "BaseData")
                        .WithMany("Units")
                        .HasForeignKey("BaseDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BattleGameWebAPI.Models.UnitTemplateData", "UnitTemplateData")
                        .WithMany()
                        .HasForeignKey("UnitTemplateDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseData");

                    b.Navigation("UnitTemplateData");
                });

            modelBuilder.Entity("BattleGameWebAPI.Models.BaseData", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("BattleGameWebAPI.Models.PlayerProfile", b =>
                {
                    b.Navigation("AccountData");
                });
#pragma warning restore 612, 618
        }
    }
}
